export const GET_COURSE_LIST = 'GET_COURSE_LIST';
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const REGISTER_COURSE = 'REGISTER_COURSE'